### ISSUE TITLE
Undefined FlutterFlowTheme

### ISSUE THREAD

**Issue by Servo2024** [FlutterFlow/flutterflow-ui#29]
By removing flutter_flow_theme.dart from the latest flutterflow-ui  v 0.3.1, all exported code from FlutterFlow uses FlutterFlowTheme, causing the entire app to have undefined issues. Please fix this.

**Comment by shayar-ghafour** [comment]
I am having the same issue too, i downgraded to the older version to solve this error. hope they fix it soon.

**Comment by Servo2024** [comment]
> I am having the same issue too, i downgraded to the older version to solve this error. hope they fix it soon.


Add these two lines:
import 'package:flutterflow_ui/flutterflow_ui.dart'
    hide TextStyleHelper, FlutterFlowTheme;
import 'package:MyFirstApp/flutter_flow/flutter_flow_theme.dart';

Change the path name to your folder name, in my case its MyFirstApp, this way you will override the broke FlutterFlowTheme file in the flutterflow_ui and resolve the conflicting files

**Comment by LennyLip** [comment]
@Servo2024 can you publicate code of flutter_flow_theme.dart please?

**update.** ok, looks like this [works ](https://github.com/CodingWithLewis/RecreatedApps/blob/208dd32d8ccbeac23f784e645f84f47f9ea0b100/sleep_app/lib/flutter_flow/flutter_flow_theme.dart#L11) ok
